-- Add finish image columns to products table
ALTER TABLE `products` 
ADD COLUMN IF NOT EXISTS `sn_image` VARCHAR(255) NULL DEFAULT NULL AFTER `pricing`,
ADD COLUMN IF NOT EXISTS `bk_image` VARCHAR(255) NULL DEFAULT NULL AFTER `sn_image`,
ADD COLUMN IF NOT EXISTS `an_image` VARCHAR(255) NULL DEFAULT NULL AFTER `bk_image`,
ADD COLUMN IF NOT EXISTS `gd_image` VARCHAR(255) NULL DEFAULT NULL AFTER `an_image`,
ADD COLUMN IF NOT EXISTS `rg_image` VARCHAR(255) NULL DEFAULT NULL AFTER `gd_image`;
